/**
* User API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models


/**
 * 
 * @param id 
 * @param username 
 * @param email 
 */
data class User (

    val id: kotlin.Int? = null,
    val username: kotlin.String? = null,
    val email: kotlin.String? = null
) {
}
